// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkifyAPI.Data.Contexts;

#nullable disable

namespace ParkifyAPI.Data.Migrations
{
    [DbContext(typeof(ParkifyDbContext))]
    partial class ParkifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ParkifyAPI.Common.Model.ParkingSpace", b =>
                {
                    b.Property<string>("SpaceNumber")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("space_number");

                    b.Property<int>("LotId")
                        .HasColumnType("int")
                        .HasColumnName("lot_id");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_occupied");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_reserved");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("plate_number");

                    b.HasKey("SpaceNumber", "LotId");

                    b.ToTable("Parking_Spaces", (string)null);
                });

            modelBuilder.Entity("ParkifyAPI.Common.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
